-- CreateTable
CREATE TABLE "AdmissionApplication" (
    "id" SERIAL NOT NULL,
    "serialNumber" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "dateOfBirth" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "age" TEXT,
    "monthOfBirth" TEXT,
    "placeOfBirth" TEXT,
    "height" TEXT,
    "weight" TEXT,
    "hometown" TEXT,
    "motherTongue" TEXT,
    "religion" TEXT,
    "dateOfAdmission" TEXT,
    "gradeLevel" TEXT NOT NULL,
    "previousSchool" TEXT,
    "parentName" TEXT NOT NULL,
    "parentOccupation" TEXT,
    "parentEmail" TEXT NOT NULL,
    "parentPhone" TEXT NOT NULL,
    "secondaryContactName" TEXT,
    "secondaryContactPhone" TEXT,
    "fatherName" TEXT,
    "fatherAddress" TEXT,
    "fatherNationality" TEXT,
    "fatherMaritalStatus" TEXT,
    "fatherPhone" TEXT,
    "fatherHouseNumber" TEXT,
    "fatherReligion" TEXT,
    "fatherOccupation" TEXT,
    "fatherPlaceOfWork" TEXT,
    "fatherEducation" TEXT,
    "fatherEmail" TEXT,
    "motherName" TEXT,
    "motherAddress" TEXT,
    "motherNationality" TEXT,
    "motherMaritalStatus" TEXT,
    "motherPhone" TEXT,
    "motherHouseNumber" TEXT,
    "motherReligion" TEXT,
    "motherOccupation" TEXT,
    "motherPlaceOfWork" TEXT,
    "motherEducation" TEXT,
    "motherEmail" TEXT,
    "livesWith" TEXT,
    "olderChildren" TEXT,
    "youngerChildren" TEXT,
    "language1" TEXT,
    "language2" TEXT,
    "language3" TEXT,
    "language4" TEXT,
    "medicalConditions" TEXT,
    "allergies" TEXT,
    "specialNeeds" TEXT,
    "doctorName" TEXT,
    "doctorPhone" TEXT,
    "hospitalName" TEXT,
    "hospitalPhone" TEXT,
    "emergencyName" TEXT NOT NULL,
    "emergencyRelationship" TEXT NOT NULL,
    "emergencyPhone" TEXT NOT NULL,
    "emergencyEmail" TEXT,
    "emergencyAddress" TEXT,
    "emergencyWhatsapp" TEXT,
    "admissionDate" TEXT,
    "photo" TEXT,
    "nhisFront" TEXT,
    "nhisBack" TEXT,
    "ghanaFront" TEXT,
    "ghanaBack" TEXT,
    "signedBooklet" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdmissionApplication_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AdmissionApplication_serialNumber_key" ON "AdmissionApplication"("serialNumber");
